[package]
name = "r2d2-diesel"
version = "0.7.1"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT"
description = "r2d2 support for Diesel"
homepage = "https://github.com/sgrif/r2d2-diesel"
repository = "https://github.com/sgrif/r2d2-diesel"

[dependencies]
r2d2 = "0.7.0"
diesel = { git = "https://github.com/jeremyletang/diesel" }

[features]
default = []
sqlite = ["diesel/sqlite"]
